# Generated by Django 5.1 on 2024-08-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_accesorio_promocion_autopromocion_accesoriopromocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='auto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.auto'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='precio_promocional',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autopromocion',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.auto'),
        ),
    ]
